#!/usr/bin/env python3
"""Generate src/chat/WaypointTable.h from the GW2 continents API.

The chat-link map id (type 0x04) is the continents-API PoI id, so this builds a
compiled-in poiId -> {name, map} table the chat window uses to label waypoint /
PoI links. Re-run after CONTENT patches that add or rename waypoints/PoIs (it is
NOT tied to the offset-recovery ritual - names are stable across build patches).

A PoI's name is only populated on its "home" floor (e.g. Crystal Oasis only on
floor 49), so we merge EVERY floor of both continents and keep each named PoI.

Usage:  python3 tools/gen_waypoints.py
Writes: src/chat/WaypointTable.h
"""
import json, os, sys, urllib.request
from concurrent.futures import ThreadPoolExecutor

CONTINENTS = [1, 2]
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "chat", "WaypointTable.h")


def fetch(url):
    with urllib.request.urlopen(url, timeout=90) as r:
        return json.load(r)


def fetch_floor(args):
    cont, fl = args
    url = f"https://api.guildwars2.com/v2/continents/{cont}/floors/{fl}"
    out = {}  # id -> (name, map)
    try:
        floor = fetch(url)
    except Exception:
        return out   # 404 / empty floors are expected for some ids
    for region in floor.get("regions", {}).values():
        for mid_s, m in region.get("maps", {}).items():
            map_name = m.get("name", "") or ""
            try:
                mid = int(mid_s)
            except (TypeError, ValueError):
                mid = -1
            for p in m.get("points_of_interest", {}).values():
                pid, name = p.get("id"), p.get("name")
                if isinstance(pid, int) and name:
                    out[pid] = (name, map_name, p.get("type") or "", mid)
    return out


# PoI type -> code used in the table (label resolved in WaypointNames.cpp).
TYPE_CODE = {"waypoint": 0, "landmark": 1, "vista": 2, "unlock": 3}

# Map-type priority: a PoI id can appear in both a public map AND a story Instance
# that reuses the geometry; prefer the public/playable map's name over the instance.
MAP_PRIO = {"Public": 3, "Center": 2, "GreenHome": 2, "BlueHome": 2, "RedHome": 2,
            "EdgeOfTheMists": 2, "Pvp": 2, "JumpPuzzle": 2, "Tutorial": 1}


def cesc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    jobs = []
    for c in CONTINENTS:
        try:
            for fl in fetch(f"https://api.guildwars2.com/v2/continents/{c}/floors"):
                jobs.append((c, fl))
        except Exception as e:
            print(f"WARN: continent {c} floor list: {e}", file=sys.stderr)
    print(f"Fetching {len(jobs)} floors...", file=sys.stderr)

    # Map id -> type, so a PoI shared by a public map and an instance prefers public.
    map_type = {}
    try:
        for m in fetch("https://api.guildwars2.com/v2/maps?ids=all"):
            map_type[m["id"]] = m.get("type", "")
    except Exception as e:
        print(f"WARN: map types: {e}", file=sys.stderr)

    def prio(mid):
        return MAP_PRIO.get(map_type.get(mid, ""), 0)

    best = {}   # id -> (priority, name, map, poi_type)
    with ThreadPoolExecutor(max_workers=12) as ex:
        for part in ex.map(fetch_floor, jobs):
            for pid, (name, mp, ptype, mid) in part.items():
                pr = prio(mid)
                cur = best.get(pid)
                if cur is None or pr > cur[0]:
                    best[pid] = (pr, name, mp, ptype)
    pois = {pid: (v[1], v[2], v[3]) for pid, v in best.items()}

    if not pois:
        print("ERROR: no PoIs fetched", file=sys.stderr)
        return 1

    maps, map_idx = [], {}
    for _id, (_n, mp, _t) in pois.items():
        if mp not in map_idx:
            map_idx[mp] = len(maps)
            maps.append(mp)
    rows = sorted(pois.items())

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/gen_waypoints.py - DO NOT EDIT.\n")
        f.write("// Source: GW2 API /v2/continents/{1,2}/floors (all floors merged).\n")
        f.write("// Regenerate after CONTENT patches that add/rename waypoints or PoIs\n")
        f.write("// (not required for offset-only build patches).\n")
        f.write("#pragma once\n#include <cstdint>\n\n")
        f.write("namespace PieUI { namespace WaypointData {\n\n")
        f.write("struct PoiEntry { uint32_t id; const char* name; uint16_t mapIdx; uint8_t type; };\n")
        f.write("// type: 0 waypoint, 1 landmark (PoI), 2 vista, 3 unlock\n\n")
        f.write("inline const char* const kMaps[] = {\n")
        for mp in maps:
            f.write(f'    "{cesc(mp)}",\n')
        f.write("};\n\n")
        f.write("// Sorted by id for binary search.\n")
        f.write("inline const PoiEntry kPois[] = {\n")
        for pid, (name, mp, typ) in rows:
            f.write(f'    {{ {pid}, "{cesc(name)}", {map_idx[mp]}, {TYPE_CODE.get(typ, 1)} }},\n')
        f.write("};\n\n")
        f.write("inline constexpr int kPoiCount = (int)(sizeof(kPois) / sizeof(kPois[0]));\n\n")
        f.write("} } // namespace PieUI::WaypointData\n")

    print(f"Wrote {OUT}: {len(rows)} PoIs, {len(maps)} maps")
    return 0


if __name__ == "__main__":
    sys.exit(main())
